import { uniqBy } from 'lodash';
import { MOCK_STATIONS_WORKERS_MAP } from '../../static/mock-data/users/stations-workers.mock';
import { MOCK_DISTRICTS_LEADERS_MAP } from '../../static/mock-data/users/districts-leaders.mock';
import { MOCK_ENGINEERS_MAP } from '../../static/mock-data/users/engineers.mock';

export const TEST_SIGN_IN_SHOULD_SUCCESS = [
  MOCK_STATIONS_WORKERS_MAP.WORKER_1,
  MOCK_STATIONS_WORKERS_MAP.WORKER_6,
  MOCK_DISTRICTS_LEADERS_MAP.LEADER_6,
  MOCK_ENGINEERS_MAP.ENGINEER_3,
  MOCK_ENGINEERS_MAP.ENGINEER_9,
];

const TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_EMAIL_CONFIRMED = [
  MOCK_STATIONS_WORKERS_MAP.WORKER_2,
  MOCK_STATIONS_WORKERS_MAP.WORKER_4,
  MOCK_STATIONS_WORKERS_MAP.WORKER_9,
  MOCK_DISTRICTS_LEADERS_MAP.LEADER_4,
  MOCK_DISTRICTS_LEADERS_MAP.LEADER_7,
  MOCK_ENGINEERS_MAP.ENGINEER_2,
  MOCK_ENGINEERS_MAP.ENGINEER_4,
  MOCK_ENGINEERS_MAP.ENGINEER_10,
  MOCK_ENGINEERS_MAP.ENGINEER_11,
  MOCK_ENGINEERS_MAP.ENGINEER_14,
];

const TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_NOT_FULL_ROLE = [
  MOCK_STATIONS_WORKERS_MAP.WORKER_7,
  MOCK_STATIONS_WORKERS_MAP.WORKER_8,
  MOCK_STATIONS_WORKERS_MAP.WORKER_9,
  MOCK_DISTRICTS_LEADERS_MAP.LEADER_5,
  MOCK_DISTRICTS_LEADERS_MAP.LEADER_7,
  MOCK_ENGINEERS_MAP.ENGINEER_11,
  MOCK_ENGINEERS_MAP.ENGINEER_14,
  MOCK_ENGINEERS_MAP.ENGINEER_16,
];

export const TEST_SIGN_IN_SHOULD_FORBIDDEN = uniqBy(
  [
    ...TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_EMAIL_CONFIRMED,
    ...TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_NOT_FULL_ROLE,
  ],
  'id',
);
