import {
  FAKE_DISTRICTS_LEADERS_MAP,
  FAKE_ENGINEERS_MAP,
  FAKE_STATIONS_WORKERS_MAP,
} from '@app/constants';
import { uniqBy } from 'lodash';

export const TEST_SIGN_IN_SHOULD_SUCCESS = [
  FAKE_STATIONS_WORKERS_MAP.WORKER_1,
  FAKE_STATIONS_WORKERS_MAP.WORKER_6,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_6,
  FAKE_ENGINEERS_MAP.ENGINEER_3,
  FAKE_ENGINEERS_MAP.ENGINEER_9,
];

const TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_EMAIL_CONDIRMED = [
  FAKE_STATIONS_WORKERS_MAP.WORKER_2,
  FAKE_STATIONS_WORKERS_MAP.WORKER_4,
  FAKE_STATIONS_WORKERS_MAP.WORKER_9,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_2,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_4,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_7,
  FAKE_ENGINEERS_MAP.ENGINEER_2,
  FAKE_ENGINEERS_MAP.ENGINEER_4,
  FAKE_ENGINEERS_MAP.ENGINEER_10,
  FAKE_ENGINEERS_MAP.ENGINEER_11,
  FAKE_ENGINEERS_MAP.ENGINEER_14,
];

const TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_NOT_FULL_ROLE = [
  FAKE_STATIONS_WORKERS_MAP.WORKER_7,
  FAKE_STATIONS_WORKERS_MAP.WORKER_8,
  FAKE_STATIONS_WORKERS_MAP.WORKER_9,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_5,
  FAKE_DISTRICTS_LEADERS_MAP.LEADER_7,
  FAKE_ENGINEERS_MAP.ENGINEER_11,
  FAKE_ENGINEERS_MAP.ENGINEER_14,
  FAKE_ENGINEERS_MAP.ENGINEER_16,
];

export const TEST_SIGN_IN_SHOULD_FORBIDDEN = uniqBy(
  [
    ...TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_EMAIL_CONDIRMED,
    ...TEST_SIGN_IN_SHOULD_FORBIDDEN_BY_NOT_FULL_ROLE,
  ],
  'id',
);
