export const USERS_ERRORS: {
  EMAILS_SHOULD_BE_UNIQUES: string;
  EMAIL_IS_EXIST: string;
  CLIENT_NOT_EXIST: string;
  DISTRICT_NOT_EXIST: string;
} = {
  EMAILS_SHOULD_BE_UNIQUES: 'EMAILS_SHOULD_BE_UNIQUES',
  EMAIL_IS_EXIST: 'EMAIL_IS_EXIST',
  CLIENT_NOT_EXIST: 'CLIENT_NOT_EXIST',
  DISTRICT_NOT_EXIST: 'DISTRICT_NOT_EXIST',
};
