export enum USER_ROLES {
  MASTER = '1',
  STATION_WORKER = '2',
  DISTRICT_LEADER = '3',
  ENGINEER = '4',
  ACCOUNTANT = '5',
}

export const DISTRICT_MEMBERS_ROLES = [
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.ENGINEER,
];

export const MEMBERS_ROLES = [
  ...DISTRICT_MEMBERS_ROLES,
  USER_ROLES.STATION_WORKER,
];

export const ALLOWED_ROLES = [
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.ENGINEER,
  USER_ROLES.STATION_WORKER,
  USER_ROLES.ACCOUNTANT,
];
