import { ENTITIES_FIELDS } from '@app/constants';

export const USERS_SORT_BY = [
  ENTITIES_FIELDS.ID,
  ENTITIES_FIELDS.NAME,
  ENTITIES_FIELDS.EMAIL,
  ENTITIES_FIELDS.CREATED_AT,
  ENTITIES_FIELDS.ROLE,
];
