import { USER_ROLES } from '@app/constants';

export const DISTRICT_MEMBERS_ROLES = [
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.ENGINEER,
];

export const MEMBERS_ROLES = [
  ...DISTRICT_MEMBERS_ROLES,
  USER_ROLES.STATION_WORKER,
];

export const ALLOWED_ROLES = [
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.ENGINEER,
  USER_ROLES.STATION_WORKER,
  USER_ROLES.ACCOUNTANT,
];
