export const USERS_ERRORS = {
  DISTRICT_LEADERS_SHOULD_HAVE_UNIQUE_DISTRICT_ID:
    'DISTRICT_LEADERS_SHOULD_HAVE_UNIQUE_DISTRICT_ID',
  STATIONS_WORKERS_SHOULD_HAVE_UNIQUE_STATION_ID:
    'STATIONS_WORKERS_SHOULD_HAVE_UNIQUE_STATION_ID',
  CLIENT_NOT_EXISTS_OR_DONT_HAVE_THIS_STATION:
    'CLIENT_NOT_EXISTS_OR_DONT_HAVE_THIS_STATION',
  STATION_ALREADY_EXISTS_AN_WORKER: 'STATION_ALREADY_EXISTS_AN_WORKER',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
  USER_HAS_OTHER_ROLE: 'USER_HAS_OTHER_ROLE',
  CANNOT_EXIST_WITHOUT_CLIENT: 'CANNOT_EXIST_WITHOUT_CLIENT',
  IMPOSSIBLE_REMOVE_STATION_FROM_WORKER:
    'IMPOSSIBLE_REMOVE_STATION_FROM_WORKER',
  IMPOSSIBLE_REMOVE_ENGINEER_FROM_DISTRICT:
    'IMPOSSIBLE_REMOVE_ENGINEER_FROM_DISTRICT',
};
