export const USERS_ERRORS: {
  DISTRICT_LEADERS_SHOULD_HAVE_UNIQUE_DISTRICT_ID: string;
} = {
  DISTRICT_LEADERS_SHOULD_HAVE_UNIQUE_DISTRICT_ID:
    'DISTRICT_LEADERS_SHOULD_HAVE_UNIQUE_DISTRICT_ID',
};
