import { NonEmptyArray } from '@app/types';
import { BID_STATUS } from '../../bids/constants';

export const BID_STATUTES_BLOCKING_CHANGE_ENGINEER_ON_DISTRICT: NonEmptyArray<BID_STATUS> =
  [
    BID_STATUS.PENDING_START_WORK_FROM_ENGINEER,
    BID_STATUS.IN_WORK,
    BID_STATUS.PENDING_REVIEW_FROM_DISTRICT_LEADER,
    BID_STATUS.FAIL_REVIEW_FROM_DISTRICT_LEADER,
  ];
