version: '3.3'

services:

  db:
    image: postgres:12
    env_file:
      - ./docker/general.env
    ports:
      - "127.0.0.1:24012:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data/

volumes:
  db_local_data:
