version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - zapad-pet

  db:
    image: postgres:12
    env_file:
      - ./docker/general.env
    volumes:
      - db_local_data:/var/lib/postgresql/data/
    networks:
      - zapad-pet

networks:
  zapad-pet:
    driver: bridge

volumes:
  db_local_data:
