export enum ENTITIES_FIELDS {
  ID = 'id',
  NAME = 'name',
  EMAIL = 'email',
  ROLE = 'role',
  EMAIL_CONFIRMED = 'emailConfirmed',
  PASSWORD = 'password',
  PASSWORD_CONFIRMATION = 'passwordConfirmation',
  CLIENT_ID = 'clientId',
  DISTRICT_ID = 'districtId',
  CREATED_AT = 'createdAt',
  UPDATED_AT = 'updatedAt',
  TOKEN = 'token',
  USERS = 'users',
  UNKNOWN = '',
}
