import { EngineerEntity, UserEntity } from '@app/entities';
import { FAKE_ENGINEERS_MAP } from '@app/constants';

const engineers: Partial<UserEntity & EngineerEntity>[] = [
  FAKE_ENGINEERS_MAP.ENGINEER_1,
  FAKE_ENGINEERS_MAP.ENGINEER_2,
  FAKE_ENGINEERS_MAP.ENGINEER_3,
  FAKE_ENGINEERS_MAP.ENGINEER_4,
  FAKE_ENGINEERS_MAP.ENGINEER_5,
  FAKE_ENGINEERS_MAP.ENGINEER_6,
  FAKE_ENGINEERS_MAP.ENGINEER_7,
  FAKE_ENGINEERS_MAP.ENGINEER_8,
  FAKE_ENGINEERS_MAP.ENGINEER_9,
  FAKE_ENGINEERS_MAP.ENGINEER_10,
  FAKE_ENGINEERS_MAP.ENGINEER_11,
  FAKE_ENGINEERS_MAP.ENGINEER_12,
  FAKE_ENGINEERS_MAP.ENGINEER_13,
  FAKE_ENGINEERS_MAP.ENGINEER_14,
  FAKE_ENGINEERS_MAP.ENGINEER_15,
  FAKE_ENGINEERS_MAP.ENGINEER_16,
];

export default engineers;
