import { StationWorkerEntity, UserEntity } from '@app/entities';
import { FAKE_STATIONS_WORKERS_MAP } from '@app/constants';

const stationWorkers: Partial<UserEntity & StationWorkerEntity>[] = [
  FAKE_STATIONS_WORKERS_MAP.WORKER_1,
  FAKE_STATIONS_WORKERS_MAP.WORKER_2,
  FAKE_STATIONS_WORKERS_MAP.WORKER_3,
  FAKE_STATIONS_WORKERS_MAP.WORKER_4,
  FAKE_STATIONS_WORKERS_MAP.WORKER_5,
  FAKE_STATIONS_WORKERS_MAP.WORKER_6,
  FAKE_STATIONS_WORKERS_MAP.WORKER_7,
  FAKE_STATIONS_WORKERS_MAP.WORKER_8,
  FAKE_STATIONS_WORKERS_MAP.WORKER_9,
];

export default stationWorkers;
