import { StationWorkerEntity, UserEntity } from '@app/entities';
import { USER_ROLES } from '@app/constants';

export const MOCK_STATIONS_WORKERS_MAP: Record<
  string,
  Partial<UserEntity & StationWorkerEntity>
> = {
  WORKER_1: {
    id: 1,
    name: 'station_worker_1',
    email: 'station_worker_1@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: 1,
    stationId: 2,
  },
  WORKER_2: {
    id: 2,
    name: 'station_worker_2',
    email: 'station_worker_2@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: false,
    clientId: 1,
    stationId: 3,
  },
  WORKER_3: {
    id: 3,
    name: 'station_worker_3',
    email: 'station_worker_3@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: 1,
    stationId: null,
  },
  WORKER_4: {
    id: 4,
    name: 'station_worker_4',
    email: 'station_worker_4@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: false,
    clientId: 2,
    stationId: 6,
  },
  WORKER_5: {
    id: 5,
    name: 'station_worker_5',
    email: 'station_worker_5@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: 2,
    stationId: 7,
  },
  WORKER_6: {
    id: 6,
    name: 'station_worker_6',
    email: 'station_worker_6@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: 3,
    stationId: 8,
  },
  WORKER_7: {
    id: 7,
    name: 'station_worker_7',
    email: 'station_worker_7@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: 4,
    stationId: null,
  },
  WORKER_8: {
    id: 8,
    name: 'station_worker_8',
    email: 'station_worker_8@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: true,
    clientId: null,
    stationId: null,
  },
  WORKER_9: {
    id: 9,
    name: 'station_worker_9',
    email: 'station_worker_9@mail.ru',
    role: USER_ROLES.STATION_WORKER,
    emailConfirmed: false,
    clientId: null,
    stationId: null,
  },
};
