export const AUTH_ERRORS: {
  CONFIRMATION_PASSWORD_NOT_MATCH: string;
  EMAIL_IS_EXIST: string;
  USER_NOT_FOUND: string;
  EMAIL_NOT_CONFIRMED: string;
  INVALID_PASSWORD: string;
  TOKEN_NOT_FOUND: string;
  EMAIL_IS_ALREADY_CONFIRMED: string;
} = {
  CONFIRMATION_PASSWORD_NOT_MATCH: 'CONFIRMATION_PASSWORD_NOT_MATCH',
  EMAIL_IS_EXIST: 'EMAIL_IS_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  EMAIL_IS_ALREADY_CONFIRMED: 'EMAIL_IS_ALREADY_CONFIRMED',
};
