export const AUTH_ERRORS: {
  CONFIRMATION_PASSWORD_NOT_MATCH: string;
  EMAIL_IS_EXIST: string;
  USER_NOT_FOUND: string;
} = {
  CONFIRMATION_PASSWORD_NOT_MATCH: 'CONFIRMATION_PASSWORD_NOT_MATCH',
  EMAIL_IS_EXIST: 'EMAIL_IS_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
};
