export const BIDS_ERRORS = {
  BID_TODO_DESC_SHOULD_BE_UNIQUE: 'BID_TODO_DESC_SHOULD_BE_UNIQUE',
  BID_NOT_FOUND: 'BID_NOT_FOUND',
  BID_HAS_THIS_STATUS: 'BID_HAS_THIS_STATUS',
  BID_FORBIDDEN_TO_EDIT: 'BID_FORBIDDEN_TO_EDIT',
  INVALID_BID_STATUS_FOR_ASSIGN_ENGINEER:
    'INVALID_BID_STATUS_FOR_ASSIGN_ENGINEER',
  INVALID_BID_STATUS_FOR_START_WORK: 'INVALID_BID_STATUS_FOR_START_WORK',
  INVALID_BID_STATUS_FOR_END_WORK: 'INVALID_BID_STATUS_FOR_END_WORK',
  BID_LOCATED_AT_STATION_IN_ANOTHER_DISTRICT:
    'BID_LOCATED_AT_STATION_IN_ANOTHER_DISTRICT',
  ENGINEER_HAVE_IS_ANOTHER_DISTRICT: 'ENGINEER_HAVE_IS_ANOTHER_DISTRICT',
  INVALID_BID_STATUS_FOR_UPDATING: 'INVALID_BID_STATUS_FOR_UPDATING',
  THIS_BID_BY_ANOTHER_ENGINEER: 'THIS_BID_BY_ANOTHER_ENGINEER',
  ALL_BID_TODOS_SHOULD_BE_COMPLETED: 'ALL_BID_TODOS_SHOULD_BE_COMPLETED',
};
