export enum BID_STATUS {
  EDITING = 'EDITING',
  AWAIT_ASSIGNMENT_TO_ENGINEER = 'AWAIT_ASSIGNMENT_TO_ENGINEER',
  AWAIT_START_WORK_AS_ENGINEER = 'AWAIT_START_WORK_AS_ENGINEER',
  IN_WORK = 'IN_WORK',
  AWAIT_CONFIRM_DISTRICT_LEADER = 'AWAIT_CONFIRM_DISTRICT_LEADER',
  AWAIT_CONFIRM_STATION_WORKER = 'AWAIT_CONFIRM_STATION_WORKER',
  RETURN_DISTRICT_LEADER = 'RETURN_DISTRICT_LEADER',
  RETURN_STATION_WORKER = 'RETURN_STATION_WORKER',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum BID_TODO_STATUS {
  PENDING = 'PENDING',
  IN_WORK = 'IN_WORK',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
}
