export const BIDS_ERRORS = {
  BID_TODO_DESC_SHOULD_BE_UNIQUE: 'BID_TODO_DESC_SHOULD_BE_UNIQUE',
  BID_NOT_FOUND: 'BID_NOT_FOUND',
  BID_HAS_THIS_STATUS: 'BID_HAS_THIS_STATUS',
  BID_FORBIDDEN_TO_EDIT: 'BID_FORBIDDEN_TO_EDIT',
  INVALID_BID_STATUS_FOR_UPDATING: 'INVALID_BID_STATUS_FOR_UPDATING',
};
