import { ENTITIES_FIELDS, SORT_DURATION_DEFAULT } from '@app/constants';

export const BIDS_GENERAL_SORT_BY = [
  ENTITIES_FIELDS.PRIORITY,
  ENTITIES_FIELDS.DEADLINE,
] as const;
export const BIDS_DATE_GENERAL_RANGES = [ENTITIES_FIELDS.DEADLINE] as const;

export const BIDS_ENGINEER_SORT_BY = BIDS_GENERAL_SORT_BY;
export const BIDS_DATE_ENGINEER_RANGES = BIDS_DATE_GENERAL_RANGES;

export const BIDS_DISTRICT_LEADER_SORT_BY = [
  ...BIDS_GENERAL_SORT_BY,
  ENTITIES_FIELDS.CREATED_AT,
  ENTITIES_FIELDS.START_WORK_AT,
  ENTITIES_FIELDS.END_WORK_AT,
] as const;
export const BIDS_DATE_DISTRICT_LEADER_RANGES = [
  ...BIDS_DATE_GENERAL_RANGES,
  ENTITIES_FIELDS.CREATED_AT,
  ENTITIES_FIELDS.START_WORK_AT,
  ENTITIES_FIELDS.END_WORK_AT,
];

export const BIDS_STATION_WORKER_SORT_BY = [
  ...BIDS_GENERAL_SORT_BY,
  ENTITIES_FIELDS.CREATED_AT,
  ENTITIES_FIELDS.CONFIRM_SUCCESS_AT,
] as const;
export const BIDS_DATE_STATION_WORKER_RANGES = [
  ...BIDS_DATE_GENERAL_RANGES,
  ENTITIES_FIELDS.CREATED_AT,
  ENTITIES_FIELDS.CONFIRM_SUCCESS_AT,
];

export const BIDS_MASTER_SORT_BY = [
  ...BIDS_DISTRICT_LEADER_SORT_BY,
  ENTITIES_FIELDS.STATION_NUMBER,
  ENTITIES_FIELDS.CONFIRM_SUCCESS_AT,
] as const;
export const BIDS_DATE_MASTER_RANGES = [
  ...BIDS_DATE_DISTRICT_LEADER_RANGES,
  ENTITIES_FIELDS.CONFIRM_SUCCESS_AT,
];

export const BIDS_LIST_DEFAULT_SORT_BY = ENTITIES_FIELDS.CREATED_AT;

export const BIDS_LIST_DEFAULT_SORT_DURATION = SORT_DURATION_DEFAULT;
