export enum BID_STATUS {
  EDITING = 'editing',
  PENDING_ASSIGNMENT_TO_ENGINEER = 'pendingAssigmentToEngineer',
  PENDING_START_WORK_FROM_ENGINEER = 'pendingStartWorkFromEngineer',
  IN_WORK = 'inWork',
  PENDING_REVIEW_FROM_DISTRICT_LEADER = 'pendingReviewFromDistrictLeader',
  PENDING_REVIEW_FROM_STATION_WORKER = 'pendingReviewFromStationWorker',
  FAIL_REVIEW_FROM_DISTRICT_LEADER = 'failReviewFromDistrictLeader',
  FAIL_REVIEW_FROM_STATION_WORKER = 'failReviewFromStationWorker',
  COMPLETED = 'completed',
  CANCEL = 'cancel',
}

export enum BID_TODO_STATUS {
  PENDING = 'PENDING',
  IN_WORK = 'IN_WORK',
  COMPLETED = 'COMPLETED',
}

export const BID_STATUS_ALLOWING_UPDATES =
  BID_STATUS.PENDING_ASSIGNMENT_TO_ENGINEER;

export const BID_STATUSES_ALLOWING_CHANGE_EDIT_STATUS = [
  BID_STATUS.EDITING,
  BID_STATUS_ALLOWING_UPDATES,
];

export const BID_STATUSES_ALLOWING_START_WORK = [
  BID_STATUS.PENDING_START_WORK_FROM_ENGINEER,
  BID_STATUS.FAIL_REVIEW_FROM_DISTRICT_LEADER,
];

export const BID_STATUSES_ALLOWING_ASSIGNMENT_TO_ENGINEER = [
  BID_STATUS.PENDING_START_WORK_FROM_ENGINEER,
  BID_STATUS.FAIL_REVIEW_FROM_STATION_WORKER,
];

export const BID_STATUSES_ALLOWING_CANCEL = [
  BID_STATUS.PENDING_ASSIGNMENT_TO_ENGINEER,
  BID_STATUS.PENDING_START_WORK_FROM_ENGINEER,
  BID_STATUS.IN_WORK,
  BID_STATUS.PENDING_REVIEW_FROM_DISTRICT_LEADER,
  BID_STATUS.PENDING_REVIEW_FROM_STATION_WORKER,
  BID_STATUS.FAIL_REVIEW_FROM_DISTRICT_LEADER,
  BID_STATUS.FAIL_REVIEW_FROM_STATION_WORKER,
];

export enum BID_EDITABLE_STATUS {
  EDITABLE = 'editable',
  UNEDITABLE = 'uneditable',
}
