export const BIDS_ERRORS = {
  BID_TODO_DESC_SHOULD_BE_UNIQUE: 'BID_TODO_DESC_SHOULD_BE_UNIQUE',
  BID_NOT_FOUND: 'BID_NOT_FOUND',
  INVALID_BID_STATUS_FOR_UPDATING: 'INVALID_BID_STATUS_FOR_UPDATING',
};
