export enum BID_STATUS {
  PENDING_IN_WORK = 'PENDING_IN_WORK',
  IN_WORK = 'IN_WORK',
  EDITING = 'EDITING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  AWAIT_CONFIRM_DISTRICT_LEADER = 'AWAIT_CONFIRM_DISTRICT_LEADER',
  AWAIT_CONFIRM_STATION_WORKER = 'AWAIT_CONFIRM_STATION_WORKER',
  RETURN_DISTRICT_LEADER = 'RETURN_DISTRICT_LEADER',
  RETURN_STATION_WORKER = 'RETURN_STATION_WORKER',
}

export enum BID_TODO_STATUS {
  PENDING = 'PENDING',
  IN_WORK = 'IN_WORK',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
}
