import { USER_ROLES } from '@app/user';

export const SIGN_UP_ALLOWED_ROLES = [
  USER_ROLES.ENGINEER,
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.STATION_WORKER,
  USER_ROLES.ACCOUNTANT,
];

export const CLIENT_MEMBERS_ROLES = [
  USER_ROLES.DISTRICT_LEADER,
  USER_ROLES.ENGINEER,
];
