export enum FILE_STORAGE_STRATEGY {
  LOCAL = 'LOCAL',
  DROPBOX = 'DROPBOX',
}

export const DEFAULT_FILE_STORAGE_STRATEGY = FILE_STORAGE_STRATEGY.LOCAL;

export const FILE_STORAGE_PROVIDER_KEY = 'FILE_STORAGE_PROVIDER_KEY';
