export const AUTH_ERRORS: {
  CONFIRMATION_PASSWORD_NOT_MATCH: string;
  EMAIL_IS_EXIST: string;
  USER_NOT_FOUND: string;
  EMAIL_NOT_CONFIRMED: string;
  INVALID_PASSWORD: string;
  TOKEN_NOT_FOUND: string;
  EMAIL_IS_ALREADY_CONFIRMED: string;
  INVALID_ROLE: string;
  EMAILS_SHOULD_BE_UNIQUES: string;
  ID_SHOULD_BE_UNIQUES: string;
  CLIENT_NOT_EXIST: string;
  DISTRICT_NOT_EXIST: string;
  DISTRICT_ID_IS_REQUIRED: string;
  CLIENT_ID_IS_REQUIRED: string;
  NO_CONNECTION_WITH_DISTRICT: string;
  NO_CONNECTION_WITH_STATION: string;
} = {
  CONFIRMATION_PASSWORD_NOT_MATCH: 'CONFIRMATION_PASSWORD_NOT_MATCH',
  EMAIL_IS_EXIST: 'EMAIL_IS_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  EMAIL_IS_ALREADY_CONFIRMED: 'EMAIL_IS_ALREADY_CONFIRMED',
  INVALID_ROLE: 'INVALID_ROLE',
  EMAILS_SHOULD_BE_UNIQUES: 'EMAILS_SHOULD_BE_UNIQUES',
  ID_SHOULD_BE_UNIQUES: 'ID_SHOULD_BE_UNIQUES',
  CLIENT_NOT_EXIST: 'CLIENT_NOT_EXIST',
  DISTRICT_NOT_EXIST: 'DISTRICT_NOT_EXIST',
  DISTRICT_ID_IS_REQUIRED: 'DISTRICT_ID_IS_REQUIRED',
  CLIENT_ID_IS_REQUIRED: 'CLIENT_ID_IS_REQUIRED',
  NO_CONNECTION_WITH_DISTRICT: 'NO_CONNECTION_WITH_DISTRICT',
  NO_CONNECTION_WITH_STATION: 'NO_CONNECTION_WITH_STATION',
};
