export const STATIONS_ERRORS = {
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  STATION_NUMBER_IS_EXIST: 'STATION_NUMBER_IS_EXIST',
  STATIONS_NUMBERS_SHOULD_BY_UNIQUE: 'STATIONS_NUMBERS_SHOULD_BY_UNIQUE',
  STATION_WORKERS_ID_SHOULD_BY_UNIQUE: 'STATION_WORKERS_ID_SHOULD_BY_UNIQUE',
  STATION_WORKER_NOT_EXIST: 'STATION_WORKER_NOT_EXIST',
  CLIENT_DONT_HAVE_THIS_WORKER: 'CLIENT_DONT_HAVE_THIS_WORKER',
  THIS_STATION_WORKER_HAVE_STATION: 'THIS_STATION_WORKER_HAVE_STATION',
  IMPOSSIBLE_REMOVE_WORKER_FROM_STATION:
    'IMPOSSIBLE_REMOVE_WORKER_FROM_STATION',
};
