import { BID_STATUS } from '../../bids/constants';
import { NonEmptyArray } from '@app/types';

export const BID_STATUTES_BLOCKING_UPDATE_STATION: NonEmptyArray<BID_STATUS> = [
  BID_STATUS.PENDING_ASSIGNMENT_TO_ENGINEER,
  BID_STATUS.PENDING_START_WORK_FROM_ENGINEER,
  BID_STATUS.IN_WORK,
  BID_STATUS.PENDING_REVIEW_FROM_DISTRICT_LEADER,
  BID_STATUS.PENDING_REVIEW_FROM_STATION_WORKER,
  BID_STATUS.FAIL_REVIEW_FROM_DISTRICT_LEADER,
  BID_STATUS.FAIL_REVIEW_FROM_STATION_WORKER,
];

export const BID_STATUTES_BLOCKING_CHANGE_WORKER_ON_STATION: NonEmptyArray<BID_STATUS> =
  [BID_STATUS.EDITING, BID_STATUS.PENDING_REVIEW_FROM_STATION_WORKER];
