import { ENTITIES_FIELDS, SORT_DURATION_DEFAULT } from '@app/constants';

export const STATIONS_LIST_DEFAULT_SORT_BY = ENTITIES_FIELDS.CREATED_AT;

export const STATIONS_LIST_DEFAULT_SORT_DURATION = SORT_DURATION_DEFAULT;

export const STATIONS_LIST_SORT_BY = [
  ENTITIES_FIELDS.NUMBER,
  ENTITIES_FIELDS.DISTRICT_NAME,
  ENTITIES_FIELDS.STATION_WORKER_NAME,
  ENTITIES_FIELDS.CLIENT_NAME,
  ENTITIES_FIELDS.CREATED_AT,
] as const;
