import { SORT_DURATION_DEFAULT } from '@app/constants';

export enum STATIONS_SORT_BY {
  NUMBER = 'number',
  DISTRICT_NAME = 'districtName',
  STATION_WORKER_NAME = 'stationWorkerName',
  CLIENT_NAME = 'clientName',
  CREATED_AT = 'createdAt',
}

export const STATIONS_LIST_DEFAULT_SORT_BY = STATIONS_SORT_BY.CREATED_AT;

export const STATIONS_LIST_DEFAULT_SORT_DURATION = SORT_DURATION_DEFAULT;

export const STATIONS_LIST_SORT_BY = [
  STATIONS_SORT_BY.NUMBER,
  STATIONS_SORT_BY.DISTRICT_NAME,
  STATIONS_SORT_BY.STATION_WORKER_NAME,
  STATIONS_SORT_BY.CLIENT_NAME,
  STATIONS_SORT_BY.CREATED_AT,
] as const;
